name: object_detector
description: Detecting and classifying object in real-time.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  camera: ^0.9.4+14
  flutter:
    sdk: flutter
  image: ^3.1.3
  path_provider: ^2.0.9
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/
